name : Build for Sonar

on:
  push:
    branches:
      - main
        pull_request:
          jobs:
            sonarcloud:
              name: SonarCloud Analysis
              runs-on: ubuntu-latest

              steps:
                # Step 1: Checkout the repository
                - uses: actions/checkout@v4
                with:
                  fetch-depth: 0  # Ensure a full history is available for a more accurate analysis

                # Step 2: Set up Java (required for SonarCloud scanner)
                - name: Set Up Java
                uses: actions/setup-java@v3.12.0
                with:
                  distribution: 'oracle'
                  java-version: '17'

                # Step 3: Set up Flutter SDK
                - name: Set Up Flutter
                uses: subosito/flutter-action@v2
                with: 
                  flutter-version: '3.24.3'
                  channel: 'stable'

                # Step 4: Install dependencies
                - name: Install Dependencies
                run: flutter pub get

                # Step 5: Run tests (optional but recommended for quality checks)
                # Uncomment if you want to run tests and generate code coverage
                - name: Run Flutter Tests
                run: flutter test --coverage

                # Step 6: Prepare SonarCloud Analysis Configuration
                - name: Set up SonarCloud
                uses: SonarSource/sonarqube-scan-action@v4
                with:
                  organization: YOUR_ORG  # Replace with your SonarCloud organization
                  token: ${{ secrets.SONAR_TOKEN }}
                  projectKey: YOUR_PROJECT_KEY  # Replace with your SonarCloud project key
                  projectName: "Flutter Android App"  # Name of the project in SonarCloud

               # Step 7: Run SonarCloud analysis
               - name: SonarCloud Analysis
               run: sonar-scanner
               env:
                 SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}